---
- name: Gather Info for PANOS VM security rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ fw01_provider }}"
    gathered_filter: "*"
    state: gathered
  register: policy_result

# - name: Print gathered facts- PANOS VM
#   ansible.builtin.debug:
#     msg: "{{ policy_result }}"


# - name: Set stats with acl info
#   ansible.builtin.set_stats:
#     data:
#       acl_data: "{{ policy_result.gathered }}"
