---

- name: Gather Info for PANOS VM virtual router
  paloaltonetworks.panos.panos_virtual_router:
    provider: "{{ fw01_provider }}"
    name: "{{ vr_name }}"
    gathered_filter: "*"
    state: gathered
  register: vr_result

# - name: Print gathered facts- PANOS VM
#   ansible.builtin.debug:
#     msg: "{{ vr_result }}"
#
#
# - name: Set stats with acl info
#   ansible.builtin.set_stats:
#     data:
#       acl_data: "{{ vr_result.gathered }}"
