---

- name: Gather facts from network devices
  hosts: atc_pan_fw01
  gather_facts: false
  connection: local

  tasks:
    - name: Include role to gather PAN-OS facts for policies
      ansible.builtin.include_role:
        name: gather_security_rules

    - name: Include role to gather PAN-OS facts for security zones
      ansible.builtin.include_role:
        name: gather_security_zones

    - name: Include role to gather PAN-OS facts for virtual routers
      ansible.builtin.include_role:
        name: gather_virtual_router
